services:
  - type: web
    name: literature-online-socket
    runtime: node
    plan: starter
    buildCommand: npm install && npm run build:server
    startCommand: npm run server:start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: BACKEND_ALLOWED_ORIGINS
        value: https://literature-online-one.vercel.app
      - key: CLIENT_ORIGIN
        value: https://literature-online-one.vercel.app
